joyvite/config/routes.rb
Joyvite::Application.routes.draw do

  root :to => 'home#index'

  match 'venues/search' => 'venues#search'
  resources :venues
end

joyvite/app/models/image.rb
class Image < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :venue
end

joyvite/app/models/venue.rb
class Venue < ActiveRecord::Base
  attr_accessible :name, :street_1, :street_2, :city, :state, :postal_code, :website, :contact_phone, :contact_email, :price, :review_count, :max_people, :rating

  has_and_belongs_to_many :venue_features
  has_many :images

  scope :cost_within_budget, -> (budget) { where(:price => 0..budget) }
end

joyvite/app/models/venue_feature.rb
class VenueFeature < ActiveRecord::Base
  attr_accessible :icon_filename, :name
  has_and_belongs_to_many :venues
end

joyvite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

joyvite/app/controllers/home_controller.rb
class HomeController < ApplicationController
  @@background_images = [ 'LizKevin-weddingHR-0308.jpg', 'LizKevin-weddingHR-0563.jpg', 'LizKevin-weddingHR-0572.jpg', 'LizKevin-weddingHR-0581.jpg', 'LizKevin-weddingHR-0703.jpg', 'LizKevin-weddingHR-0742.jpg', 'LizKevin-weddingHR-0743.jpg', '_DSC0148.JPG', 'the Napa Valley wedding of Leslie and Brian-1200_LB28754.jpg', 'the Napa Valley wedding of Leslie and Brian-1201IMG_5884.jpg', 'the Napa Valley wedding of Leslie and Brian-1231IMG_0349.jpg', 'wedding3.jpg', 'wedding6.jpg' ];

  def index
    image_index = rand(@@background_images.length)
    @background_image = @@background_images[image_index]
  end

end

joyvite/app/controllers/venue_controller.rb
class VenueController < ApplicationController

  def search
    query = params[:query]

    @venues = Venue
    #@venues = @venues.available_from(query[:date_from]) if query.key ? :date_from
    #@venues = @venues.available_to(query[:date_to]) if query.key ? :date_to
    @venues = @venues.costs_less_than(query[:budget].to_i) unless query[:budget].blank?

    if @venues == Venue
      @venues = Venue.all
    end
  end

  private
  def parse_location location_string
    location_string.strip!
    location = {}
    postal = location_string.match(/[0-9]{5}(?:-?[0-9]{4})?/)
    if postal
      location[:postal_code] = postal[0]
    else
      state = location_string.match(/(?:^|\s+|,\s*)([a-zA-Z]{2})$/)
      if state
        location[:state] = state[1]
        city_end = state.begin(0)
        location[:city] = location_string[0, city_end] if city_end >= 1
      else
        location[:city] = location_string
      end
    end
    return location
  end
end

joyvite/app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def show
    @venue = Venue.find(params[:id])
  end

  def search
    query = params[:query]

    @outside_counts = {}
    @venues = Venue
    if not query[:budget].blank?
      budget = query[:budget].to_i
      @venues = @venues.cost_within_budget(budget)
      @outside_counts[:budget] = "#{Venue.where('price > ?', budget).count} outside your budget"
    end

    @venues = @venues.order('price')
  end

  private
  def parse_location location_string
    location_string.strip!
    location = {}
    postal = location_string.match(/[0-9]{5}(?:-?[0-9]{4})?/)
    if postal
      location[:postal_code] = postal[0]
    else
      state = location_string.match(/(?:^|\s+|,\s*)([a-zA-Z]{2})$/)
      if state
        location[:state] = state[1]
        city_end = state.begin(0)
        location[:city] = location_string[0, city_end] if city_end >= 1
      else
        location[:city] = location_string
      end
    end
    return location
  end
end

joyvite/app/helpers/application_helper.rb
module ApplicationHelper
end

joyvite/app/helpers/home_helper.rb
module HomeHelper
end

joyvite/app/helpers/venue_helper.rb
module VenueHelper
end

joyvite/app/views/home/index.erb
<div class="home-search-container">
  <%= form_for :query, :as => :post, :url => 'venues/search', :html => { :class => 'home-search' }  do |f| %>
    <%= f.text_field :budget, :class => 'home-search-budget', :placeholder => 'Budget' %>
    <div id="dateRangeContainer" class="home-search-date-range">
      <%= f.text_field :date_from, :class => 'home-search-date-from date-input', :placeholder => 'Start Date' %>
      <img src="/assets/datepicker_icon.png" class="datepicker-icon" />
      <%= f.text_field :date_to, :class => 'home-search-date-to date-input', :placeholder => 'End Date' %>
      <img src="/assets/datepicker_icon.png" class="datepicker-icon" />
    </div>
    <%= f.submit 'Find Venues', :class => 'home-search-submit' %>
  <% end %>
</div>

<div id="rangePickerContainer" class="date-range-picker-container">
  <div id="rangeFromContainer" class="date-range-from-container"></div>
  <div id="rangeToContainer" class="date-range-to-container"></div>
  <div class="date-range-button-container">
    <button type="button" id="closeRangePicker">Close</button>
  </div>
</div>

<div class="selling_point selling_point_simplify">
  <h1>SIMPLIFY</h1>
  <p>
    Search Napa Valley wedding venues in one clean, user-friendly site with multiple filters to meet your needs.  There's no need to browse through countless sites when you use Joyvite.
  </p>
</div>

<div class="selling_point selling_point_money">
  <h1>SAVE MONEY</h1>
  <p>
    Couples can spend hundreds of dollars hiring a wedding planner to find them a venue.  Save money with one click.
  </p>
</div>

<div class="selling_point selling_point_connect">
  <h1>CONNECT</h1>
  <p>
    Connect directly with wedding venue managers, schedule site visits, and even make tentative bookings.  Share bookmarked results with friends and family as you plan your special day.
  </p>
</div>

<% content_for :script do %>
<script>
  jQuery(function ($) {
    rangeContainer = $('#dateRangeContainer');
    pickerContainer = $('#rangePickerContainer');
    fromPicker = $('#rangeFromContainer');
    toPicker = $('#rangeToContainer');

    fromPicker.datepicker({
      changeYear: true,
      minDate: new Date(),
      onSelect: function (v) {
        $('#query_date_from').val(v);
        var d = new Date(v);
        var toMin = new Date(d.getFullYear(), d.getMonth(), d.getDate() + 1);
        var toDate = toPicker.datepicker('getDate');
        if (toDate < toMin) {
          toPicker.datepicker('setDate', toMin);
        }
        toPicker.datepicker('option', 'minDate', toMin);
      }
    });
    $('#rangeToContainer').datepicker({
      changeYear: true,
      minDate: new Date(),
      onSelect: function (v) {
        $('#query_date_to').val(v);
        var d = new Date(v);
        var fromMax = new Date(d.getFullYear(), d.getMonth(), d.getDate() - 1);
        var fromDate = fromPicker.datepicker('getDate');
        if (fromDate > fromMax) {
          fromPicker.datepicker('setDate', fromMax);
        }
        fromPicker.datepicker('option', 'maxDate', fromMax);
      }
    });
    $('#closeRangePicker').button().click(function () {
      pickerContainer.hide();
    });

    rangeContainer.bind('click', function () {
      var offset = rangeContainer.offset();
      pickerContainer
        .css({
          top: offset.top + rangeContainer.outerHeight(),
          left: offset.left
        })
        .show();
    });

    $('body').click(function (ev) {
      var target = $(ev.target);
      if (target.closest('#dateRangeContainer,#rangePickerContainer,#ui-datepicker-div,.ui-datepicker-header').length > 0) {
        return;
      }
      pickerContainer.hide();
    });
  });
</script>
<% end %>

joyvite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joyvite</title>
  <link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" media="all" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="header">
    <div class="header-links">
      <a href="#">login</a>
      <a href="#">sign up</a>
      <a href="#">help</a>
    </div>

    <a href="/"><img class="logo" src="/assets/logo.png" alt="Joyvite" /></a>
  </div>

  <div class="main">
    <%= yield %>
  </div>

  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <%= javascript_include_tag "application" %>
  <%= yield :script %>
</body>
</html>

joyvite/app/views/venues/_filters.erb
<ul class="filter-list">
  <li class="filter-list-item">
    <button id="budgetFilter" class="dropdown-trigger filter-dropdown">Budget</button>
  </li>
  <li class="filter-list-item">
    <button id="dateRangeFilter" class="dropdown-trigger filter-dropdown">Date Range</button>
  </li>
  <li class="filter-list-item">
    <button id="capacityFilter" class="dropdown-trigger filter-dropdown">Capacity</button>
  </li>
  <li class="filter-list-item">
    <button id="ratingFilter" class="dropdown-trigger filter-dropdown">Rating</button>
  </li>
  <li class="filter-list-item">
    <button id="venueTypeFilter" class="dropdown-trigger filter-dropdown">Type of Venue</button>
  </li>
  <li class="filter-list-item">
    <button id="amenitiesFilter" class="dropdown-trigger filter-dropdown">Amenities</button>
  </li>
</ul>

joyvite/app/views/venues/_map.erb
<div id="venueMap" class="venue-map" src="/assets/venue/map_mockup.png"></div>

joyvite/app/views/venues/search.erb
<div class="sidebar">
  <%= render partial: 'map' %>
  <%= render partial: 'filters' %>
</div>

<div class="results-panel">
  <% if @venues.empty? %>
    No venues found.
  <% else %>
    <div class="results-header">
      <span class="sort-container">
        sort by <button id="sortBy" class="dropdown-trigger sort-by-dropdown">Price</button>
      </span>
      <span class="search-matching-count">
        <%= @venues.length %> venues
      </span>
      <% if not @outside_counts.keys.empty? %>
        <span class="search-outside-count">
          (<% @outside_counts.each do |k,v| %><%= v %><% end %>)
        </span>
      <% end %>
    </div>
    <ul class="venue-list" data-venues="<%= @venues.to_json %>">
    <% @venues.each do |v| %>
      <li class="venue-list-item">
        <div class="venue-list-item-image image-carousel first-image" data-venue-id="<%= v.id %>" data-venue-images="<%= v.images.to_json(:only => [:id]) %>">
          <img class="image-carousel-image" src="/assets/vendors/<%= v.images[0].id %>.jpg" />
        </div>
        <div class="package-details">
          <div class="package-price">
            <%= number_with_precision(v.price, :precision => 0) %>
          </div>
          <div class="package-price-label">minimum package</div>
          <div class="package-max-people">
            <div class="package-max-people-count"><%= v.max_people %></div>
            <div class="package-max-people-label">people max</div>
          </div>
          <button class="bookmark">BOOKMARK</button>
        </div>
        <%= link_to v.name, venue_path(v), class: 'venue-name' %>
        <div class="venue-location"><%= v.city %></div>
        <div class="venue-options">
          <% v.venue_features.each do |feat| %>
            <img src="/assets/venue/<%= feat.icon_filename %>" title="<%= feat.name %>" alt="<%= feat.name %>" />
          <% end %>
        </div>
        <div class="venue-reviews-summary">
          <div class="venue-review-message">"Lorem ipsum doler sit amet..."</div>
          <div class="venue-review-stars" title="<%= v.rating %> <%= v.rating == 1 ? 'star' : 'stars'%>">
            <% for i in 1..v.rating %>
              <img src="/assets/venue/star_on.png" />
            <% end %>
          </div>
          <%= link_to(venue_path(v), { :class => 'venue-reviews-link' }) do %>
            <%= v.review_count %> reviews
          <% end %>
        </div>
      </li>
    <% end %>
    </ul>
  <% end %>
</div>

<% content_for :script do %>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCNw8Yvbw_9iP53dWK7nzL4hkEF0vzLiDM&sensor=false"></script>
  <script>
    var geocoder;

    function mapVenue(map, venue) {
      var address = [venue.street_1, venue.city, venue.state].join(',') + ' ' + venue.postal_code;
      geocoder.geocode({ address: address }, function (result, status) {
        if (status == google.maps.GeocoderStatus.OK && result.length == 1) {
          var marker = new google.maps.Marker({
            map: map,
            position: result[0].geometry.location
          });
        }
      });
    }

    google.maps.event.addDomListener(window, 'load', function () {
      geocoder = new google.maps.Geocoder();

      var map = new google.maps.Map(document.getElementById('venueMap'), {
        center: new google.maps.LatLng(38.3047, -122.2989),
        zoom: 8,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      });

      var venues = JSON.parse($('.venue-list').attr('data-venues'));
      for (var i = 0; i < venues.length; i++) {
        mapVenue(map, venues[i]);
      }
    });

    jQuery(function ($) {
      function changeImage(ev) {
        var target = $(ev.target);
        var changeBy = target.closest('.carousel-button').data('change-by');
        var carousel = target.closest('.image-carousel');

        var newIndex = carousel.data('current-image-index') + changeBy;
        var images = carousel.data('images');
        var image = carousel.find('.image-carousel-image');
        image.attr('src', '/assets/vendors/' + images[newIndex].id + '.jpg');
        carousel.data('current-image-index', newIndex);
        carousel.toggleClass('first-image', newIndex == 0);
        carousel.toggleClass('last-image', newIndex == images.length - 1);
      }

      function carouselize(carousel, images) {
        carousel.data('images', images);
        carousel.data('current-image-index', 0);

        var previousButton = $('<div class="carousel-button carousel-button-previous"></div>')
          .data('change-by', -1)
          .click(changeImage);
        var nextButton = $('<div class="carousel-button carousel-button-next"></div>')
          .data('change-by', 1)
          .click(changeImage);

        carousel
          .append(previousButton)
          .append(nextButton);

      }

      $('.dropdown-trigger').button();
      $('.bookmark').button();

      $('.image-carousel').each(function (i, el) {
        var carousel = $(el);
        var images = JSON.parse(carousel.attr('data-venue-images'));
        console.log('Images ' + i + ': ');
        console.log(images);
        if (images.length > 1) {
          carouselize(carousel, images);
        }
      });
    });
  </script>
<% end %>

joyvite/app/views/venues/show.erb
<div class="details-mockup"></div>